#!/bin/bash

if [ $# -ne 1 ]; then
    echo "Usage: badmalloc (on/off)"
elif [ "$1" = "on" ]; then
    make -C ~/.bin/data/
    export LD_PRELOAD="/home/navenn_t/.bin/data/badmalloc.so"
elif [ "$1" = "off" ]; then
    unset LD_PRELOAD
else
    echo "badmalloc: bad option :c"
fi
