#!/bin/bash

GREY='\033[1;32m'
NC='\033[0m'
USR='thomas.navennec@epitech.eu'
LOGIN='navenn_t'

if [ $# -ne 1 ]; then
    echo -e ${GREY}"~~~ Please enter a name for the repository ~~~"${NC}
    exit 1
fi
echo -e ${GREY}"~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~"${NC}
echo -e ${GREY}"~~~~      CREATION DEPOT GIT      ~~~~"${NC}
echo -e ${GREY}"~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~"${NC}
blih -u ${USR} repository create "$1"

echo -e ${GREY}"~~~ Droits ramassage-tek ~~~"${NC}
blih -u ${USR} repository setacl "$1" ramassage-tek r

echo -e ${GREY}"~~ Would you like to clone the repo here? (Y/n) ~~~"${NC}
read -n 1 clone

if [ "$clone" != "n" ] && [ "$clone" != "N" ]; then
    git clone git@git.epitech.eu:/${LOGIN}/$1
fi

echo -e ${GREY}"~~ Everything done, have a nice day ~~~"${NC}
