#!/bin/bash

mkdir -p include
mkdir -p lib/my_printf

cp ~/libfiles/include/*.h include/
cp ~/libfiles/lib/*.c ./lib/
cp ~/libfiles/lib/Makefile ./lib/
cp ~/libfiles/lib/my_printf/* ./lib/my_printf/

make -C./lib/

cp ~/libfiles/Makefile .

echo Your will has been carried out c:
