#!/bin/bash

configs=("dunst" "i3" "nitrogen" "polybar" "rofi" "terminator" "compton")
homes=(".bin/" ".zshenv" ".zshrc")

rm -rf ~/dotfiles/*
rm -rf ~/dotfiles/.bin/

mkdir -p ~/dotfiles/

for i in ${configs[@]} ; do :
    cp -r ~/.config/$i ~/dotfiles/
done

for i in ${homes[@]}
do
    :
    cp -r ~/$i ~/dotfiles/
done
