#!/bin/bash

configs=("conky" "dunst" "i3" "nitrogen" "polybar" "rofi" "terminator" "compton")

homes=(".bin/" ".zshenv" ".zshrc")

cprogs=("batteryd")

for i in "${configs[@]}"
do
    :
    cp -r ~/.config/$i ~/dotfiles/
done

for i in "${homes[@]}"
do
    :
    cp -r ~/$i ~/dotfiles/
done

for i in "${cprogs[@]}"
do
    :
    cp -r ~/Programming/c/$i ~/dotfiles/
done
