#!/bin/sh

B='#00000020'  # blank
C='#ffffff40'  # clear ish
D='#ff00ffff'  # default
W='#c00000c0'  # wrong
V='#eeeeeebb'  # verifying

i3lock \
--insidevercolor=$C   \
--ringvercolor=$V     \
\
--insidewrongcolor=$C \
--ringwrongcolor=$W   \
\
--insidecolor=$B      \
--ringcolor=$D        \
--linecolor=$B        \
--separatorcolor=$D   \
\
--verifcolor=$V        \
--wrongcolor=$D        \
--timecolor=$D        \
--datecolor=$D        \
--layoutcolor=$D      \
--keyhlcolor=$V       \
--bshlcolor=$W        \
\
--screen 1            \
--blur 4              \
--clock               \
--indicator           \
--timestr="%H:%M:%S"  \
--datestr="%A, %m %Y" \
--veriftext="..." \
--wrongtext="" \
--noinputtext="" \

# --textsize=20
# --modsize=10
# --timefont=comic-sans
# --datefont=monofur
# etc
