#!/bin/bash

git add -A

if [ $# -eq 0 ]; then
	git commit -am "Quick fix, no comment"
elif [ $# -ge 1 ]; then
	git commit -am "${1}"
fi

branch="$(git symbolic-ref --short -q HEAD)"
git push origin $branch